version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    restart: unless-stopped
    command: uvicorn server.asgi:application --host 0.0.0.0 --reload
    depends_on:
      - db
    volumes:
      - ./backend:/home/server:z
      - static_volume:/home/server/static
      - media_volume:/home/server/media
    ports:
      - "8000:8000"
    env_file:
      - .envs/development/web.env
      - .envs/development/db.env
    networks:
      - project-network

  db:
    image: postgres:11.8
    networks:
      - project-network
    env_file:
      - .envs/development/db.env

networks:
  project-network:
    name: keeper-network

volumes:
  mysql_data: { }
  static_volume: { }
  media_volume: { }
